[linux]
arr01
minecraft01
jellyfin01
netbox01
nginxproxy01
pihole01
guacamole01
ansible01

[update]
arr01
minecraft01
jellyfin01
netbox01
nginxproxy01
pihole01
guacamole01

[docker]
arr01
minecraft01
jellyfin01
netbox01
nginxproxy01
pihole01
guacamole01
