- name: Play for importing common configuration
  become: true
  hosts: linux
  vars_files:
    - vault.yml
  tasks:

    - name: Import common role
      ansible.builtin.import_role:
        name: common

- name: PLay for importing ansible controller configuration
  become: true
  hosts: ansible01
  tasks:

    - name: Import ansible-controller role
      ansible.builtin.import_role:
        name: ansible-controller

- name: Play for importing arr configuration
  become: true
  hosts: arr01
  vars_files:
    - vault.yml
  tasks:

    - name: Import arr role
      ansible.builtin.import_role:
        name: arr

- name: Play for importing jellyfin configuration
  become: true
  hosts: jellyfin01
  tasks:

    - name: Import jellyfin role
      ansible.builtin.import_role:
        name: jellyfin

- name: Play for importing netbox configuration
  become: true
  hosts: netbox01
  vars_files:
    - vault.yml
  tasks:

    - name: Import netbox role
      ansible.builtin.import_role:
        name: netbox

- name: Play for importing pihole configuration
  become: true
  hosts: pihole01
  vars_files:
    - vault.yml
  tasks:

    - name: Import pihole role
      ansible.builtin.import_role:
        name: pihole

- name: Play for importing guacamole configuration
  become: true
  hosts: guacamole01
  vars_files:
    - vault.yml
  tasks:

    - name: Import guacamole role
      ansible.builtin.import_role:
        name: guacamole

- name: Play for importing caddy configuration
  become: true
  hosts: caddy01
  vars_files:
    - vault.yml
  tasks:

    - name: Import caddy role
      ansible.builtin.import_role:
        name: caddy
