netbox_url: "https://netbox.troncraft.xyz"
netbox_prefix: "192.168.10.0/24"
netbox_tenant: "homelab-tenant"
netbox_cluster: "pve"
vm_template: "ubuntu-2404-cloudinit-template"




# Netbox
netbox_role: "virtual-server"
netbox_site: "homelab-site"
netbox_platform: "ubuntu-linux"

# VM Template
vm_template_image_name: "ubuntu-24.04-server-cloudimg-amd64.img"
vm_template_image_url: "https://cloud-images.ubuntu.com/daily/server/releases/24.04/release/ubuntu-24.04-server-cloudimg-amd64.img"
vm_template_id: "10002"

# proxmox
proxmox_url: "192.168.10.188"
