netbox_url: "https://demo.netbox.dev"
netbox_api_key: "5a9ba2644ee839c3d8fe86761cb2371b07799afa"
netbox_prefix: "10.112.148.0/28"
netbox_tenant: "stark-industries"
ansible_hostname: "trongull01"
netbox_cluster: "DO-AMS3"
vm_name: "{{ ansible_hostname }}"
vm_cpus: "4"
vm_memory: "16384" # MB
vm_disk_size: "80" # GB
vm_template: "ubuntu-2404-cloudinit-template"
vm_storage: "local-lvm"




# Netbox
netbox_role: "virtual-server"
netbox_site: "aai"
netbox_platform: "ubuntu-linux"
