- name: Check if VMs already exists
  ansible.builtin.shell: qm list | grep {{ inventory_hostname }} | cut -d ' ' -f 8
  ignore_errors: true
  register: vm_id_check
  changed_when: false
  delegate_to: proxmox01

- name: Import template creation tasks
  ansible.builtin.import_tasks:
    file: template.yml
  delegate_to: proxmox01
  run_once: true

- name: Import netbox tasks
  ansible.builtin.import_tasks:
    file: netbox.yml
  delegate_to: localhost

- name: Import VM provisioning tasks
  ansible.builtin.import_tasks:
    file: provision.yml
  delegate_to: localhost

- name: Import OS configuration tasks
  when: not vm_id_check.stdout | length > 0
  become: true
  ansible.builtin.import_tasks:
    file: os_configuration.yml
  vars:
    ansible_user: cloudinit
    ansible_ssh_pass: "123"
    ansible_become_pass: "123"
