- name: Block for provisioning VM - {{ ansible_hostname }}
  delegate_to: localhost
  block:

    - name: Create VM in Netbox - {{ ansible_hostname }}
      netbox.netbox.netbox_virtual_machine:
        netbox_url: "{{ netbox_url }}"
        netbox_token: "{{ netbox_api_key }}"
        data:
          name: "{{ vm_name }}"
          vcpus: "{{ vm_cpus | int }}"
          memory: "{{ vm_memory | int }}"
          cluster: "{{ netbox_cluster }}"
          virtual_machine_role: "{{ netbox_role }}"
          site: "{{ netbox_site }}"
          platform: "{{ netbox_platform }}"
          tenant: "{{ netbox_tenant }}"
          status: active

    - name: Create network interface - {{ ansible_hostname }}
      netbox.netbox.netbox_vm_interface:
        netbox_url: "{{ netbox_url }}"
        netbox_token: "{{ netbox_api_key }}"
        data:
          virtual_machine: "{{ ansible_hostname }}"
          name: eth0
          enabled: true

    - name: Reserve IP address - {{ ansible_hostname }}
      netbox.netbox.netbox_ip_address:
        netbox_url: "{{ netbox_url }}"
        netbox_token: "{{ netbox_api_key }}"
        data:
          prefix: "{{ netbox_prefix }}"
          status: active
          tenant: "{{ netbox_tenant }}"
          dns_name: "{{ ansible_hostname }}.jagvettefan.com"
          assigned_object:
            virtual_machine: "{{ ansible_hostname }}"
            name: eth0
        state: present
      register: vm_ip

    - name: debug vm_ip_facts
      ansible.builtin.debug:
        var: vm_ip

    - name: Assign primariy IP to VM in Netbox - {{ ansible_hostname }}
      netbox.netbox.netbox_virtual_machine:
        netbox_url: "{{ netbox_url }}"
        netbox_token: "{{ netbox_api_key }}"
        data:
          name: "{{ vm_name }}"
          primary_ip4: "{{ vm_ip.ip_address.address }}"

    #- name: Provision VM in proxmox - {{ ansible_hostname }}
    #  community.general.proxmox.kvm:
    #    api_host: "{{ proxmox_url }}"
    #    api_user: "ansible@pam"
    #    api_password: "{{ proxmox_ansible_password }}"
    #    node: "pve"
    #    name: "{{ vm_name }}"
    #    net:
    #      'virtio,bridge=vmbr0'
    #    bios: ovmf
    #    scsilhw: "virtio-scsi-pci"
    #    clone: "{{ vm_template }}"
    #    storage: "{{ vm_storage }}"
    #    cores: "{{ vm_cpus }}"
    #    memory: "{{ vm_memory }}" # MB
    #    virtio:
    #      - "local-lvm:{{ vm_disk_size }},format=qcow2"
    #    efidisk0:
    #      storage: "local-lvm"
    #      format: "raw"
    #      efitype: "4m"
    #      pre_enrolled_keys: false
    #      state: present
