- name: Install python packages
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  with_items:
    - python3

- name: Install qemu guest agent
  ansible.builtin.package:
    name: qemu-guest-agent
    state: present

- name: Import firewall tasks
  ansible.builtin.import_tasks:
    file: firewall.yml

- name: Import user tasks
  ansible.builtin.import_tasks:
    file: users.yml

- name: Import SSH tasks
  ansible.builtin.import_tasks:
    file: ssh.yml

- name: Import sudoers tasks
  ansible.builtin.import_tasks:
    file: ssh.yml

- name: Import DNS tasks
  ansible.builtin.import_tasks:
    file: dns.yml
