# VM Specifications
vm_cpus: "2"
vm_memory: "4096" # MB
vm_disk_size: "60" # GB

# Firewall
common_host_firewall_rules:
  - { port: "80", protocol: "tcp" }
  - {port: "443", protocol: "tcp"}

# Netbox
netbox_version: "v4.2.5-3.2.0"


ansible_host: "192.168.10.25"
