- name: Install docker
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  with_items:
    - docker.io
    - docker-compose-v2

- name: Create dockerfiles group
  ansible.builtin.group:
    name: dockerfiles
    gid: 1500
    state: present

- name: Create dockeruser user
  ansible.builtin.user:
    name: dockeruser
    state: present
    shell: /usr/bin/nologin
    system: true
    expires: -1
    password: "!"
    password_expire_max: 99999
    create_home: false
    uid: 900
    group: dockerfiles

- name: Create directories for netbox
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: root
    mode: '0770'
  with_items:
    - /opt/netbox
    - /opt/netbox/netbox
    - /opt/netbox/netbox/media
    - /opt/netbox/config/netbox-config
    - /opt/netbox/env
    - /opt/netbox/caddy

- name: Template netbox docker-compose file
  ansible.builtin.template:
    src: docker-compose.yml.j2
    dest: /opt/netbox/docker-compose.yml
    owner: root
    group: root
    mode: '0770'

- name: Template out netbox docker-compose override file
  ansible.builtin.template:
    src: docker-compose.override.yml.j2
    dest: /opt/netbox/docker-compose.override.yml
    owner: root
    group: root
    mode: '0770'

- name: Template out caddyfile
  ansible.builtin.template:
    src: caddyfile.j2
    dest: /opt/netbox/caddy/caddyfile
    owner: root
    group: root
    mode: '0770'

- name: Template out postgres env file
  ansible.builtin.template:
    src: postgres.env.j2
    dest: /opt/netbox/env/postgres.env
    owner: root
    group: root
    mode: '0770'

- name: Template out redis env file
  ansible.builtin.template:
    src: redis.env.j2
    dest: /opt/netbox/env/redis.env
    owner: root
    group: root
    mode: '0770'

- name: Template out redis cache env file
  ansible.builtin.template:
    src: redis-cache.env.j2
    dest: /opt/netbox/env/redis-cache.env
    owner: root
    group: root
    mode: '0770'

- name: Template out netbox env file
  ansible.builtin.template:
    src: netbox.env.j2
    dest: /opt/netbox/env/netbox.env
    owner: root
    group: root
    mode: '0770'

- name: Start netbox container
  community.docker.docker_compose_v2:
    project_src: /opt/netbox
    state: present

- name: Wait for netbox to become available
  ansible.builtin.uri:
    url: "https://netbox.troncraft.xyz"
    method: GET
    timeout: 10
  register: netbox_status
  retries: 200
  delay: 10
  until: netbox_status.status == 200
  ignore_errors: true

- name: Import netbox post install tasks
  ansible.builtin.import_tasks:
    file: netbox.yml
  delegate_to: localhost
