- name: Create netbox device role - Virtual Server
  netbox.netbox.netbox_device_role:
    netbox_url: "{{ netbox_url }}"
    netbox_token: "{{ netbox_api_key }}"
    data:
      name: "Virtual Server"
      slug: "virtual-server"
      description: "Role for virtual machines"
      vm_role: true
    state: present
    validate_certs: false

- name: Create netbox site - Homelab Site
  netbox.netbox.netbox_site:
    netbox_url: "{{ netbox_url }}"
    netbox_token: "{{ netbox_api_key }}"
    data:
      name: "Homelab Site"
      slug: "homelab-site"
      description: "Site for my homelab"
    state: present
    validate_certs: false

- name: Create Proxmox cluster cluster_type
  netbox.netbox.netbox_cluster_type:
    netbox_url: "{{ netbox_url }}"
    netbox_token: "{{ netbox_api_key }}"
    data:
      name: "Proxmox"
      slug: "proxmox"
    state: present
    validate_certs: false

- name: Create netbox cluster - pve
  netbox.netbox.netbox_cluster:
    netbox_url: "{{ netbox_url }}"
    netbox_token: "{{ netbox_api_key }}"
    data:
      name: "pve"
      cluster_type: "proxmox"
    state: present
    validate_certs: false

- name: Create netbox platform - Ubuntu Linux
  netbox.netbox.netbox_platform:
    netbox_url: "{{ netbox_url }}"
    netbox_token: "{{ netbox_api_key }}"
    data:
      name: "Ubuntu Linux"
      slug: "ubuntu-linux"
    state: present
    validate_certs: false

- name: Create netbox tenant - Homelab Site
  netbox.netbox.netbox_tenant:
    netbox_url: "{{ netbox_url }}"
    netbox_token: "{{ netbox_api_key }}"
    data:
      name: "Homelab Tenant"
      slug: "homelab-tenant"
    state: present
    validate_certs: false

- name: Create netbox prefix - 192.168.10.0/24
  netbox.netbox.netbox_prefix:
    netbox_url: "{{ netbox_url }}"
    netbox_token: "{{ netbox_api_key }}"
    data:
      prefix: 192.168.10.0/24
      tenant: "homelab-tenant"
      status: active
      is_pool: false
    state: present
    validate_certs: false

- name: Reserve address range in prefix - 192.168.10.0/24
  netbox.netbox.netbox_ip_address:
    netbox_url: "{{ netbox_url }}"
    netbox_token: "{{ netbox_api_key }}"
    data:
      address: "192.168.10.{{ item }}/24"
      status: reserved
      tenant: "homelab-tenant"
    state: present
    validate_certs: false
  loop: "{{ range(1, 25) | list }}"

- name: Reserve DHCP address range in prefix - 192.168.10.0/24
  netbox.netbox.netbox_ip_address:
    netbox_url: "{{ netbox_url }}"
    netbox_token: "{{ netbox_api_key }}"
    data:
      address: "192.168.10.{{ item }}/24"
      status: dhcp
      tenant: "homelab-tenant"
    state: present
    validate_certs: false
  loop: "{{ range(100, 255) | list }}"
